### ISSUE TITLE
bug: error on cursor move when helm-ls enabled

### ISSUE THREAD

**Issue by eshepelyuk** [qvalentin/helm-ls.nvim#4]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Operating system/version

Linux 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Using `vim-plug` as plugin manager.

### Describe the bug

After opening a file - I see this error when moving a cursor or clicking with mouse
![image](https://github.com/user-attachments/assets/dd8ede62-ca73-4739-897b-f7718cff55eb)

### Steps To Reproduce

1. Install plugin with default config
```lua
local lspconfig = require('lspconfig')
lspconfig.helm_ls.setup({})
require("helm-ls").setup({})

```
2. Open helm template, i.e. file from `tempaltes/` fodler of a chart.
3. Move cursor or click with mouse in the middle of the file.

### Expected Behavior

No errors shown.

**Comment by eshepelyuk** [comment]
Sorry, but I think the fix should be to to remove all code from `plugin/helm-ls.lua` file.
Autocommand should be created only by calling `setup()` function,
When plugin enabled without invoking `setup()` - it only adds filetype detection.

This also help to remove code duplication in `plugin/helm-ls.lua` and `setup()`.

Because currently, I am forced to add call to `setup()` to avoid this error.
![image](https://github.com/user-attachments/assets/69e359ae-4c5f-4489-8184-d71bbde18f30)

**Comment by eshepelyuk** [comment]
NP opening a PR, but plz suggest what should I put there ?
Is emptying `plugin/helm-ls.lua` enough ?

**Comment by qvalentin** [comment]
Sorry if im a bit uncooperative. I think i will just get back to you when I'm back on a PC and not on mobile.
But thanks for the feedback <3

**Comment by eshepelyuk** [comment]
> Sorry if im a bit uncooperative. I think i will just get back to you when I'm back on a PC and not on mobile. But thanks for the feedback <3

https://github.com/qvalentin/helm-ls.nvim/pull/5
